"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-17 23:51:33.108359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default='skill', nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata', sa.Text(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tags',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('bg', sa.Text(), nullable=False),
    sa.Column('text_color', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('entity_items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default='command', nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata', sa.Text(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('tag_key', sa.Text(), nullable=True),
    sa.Column('due', sa.Text(), nullable=True),
    sa.Column('status_key', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['status_key'], ['statuses.key'], ),
    sa.ForeignKeyConstraint(['tag_key'], ['tags.key'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('entity_items')
    op.drop_table('tags')
    op.drop_table('statuses')
    op.drop_table('entities')
    # ### end Alembic commands ###
