"""drop unused metadata columns

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-19 01:36:18.462661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concepts', 'metadata')
    op.drop_column('topics', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False))
    op.add_column('concepts', sa.Column('metadata', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
