"""queues instead of tags, task number, drop due

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-21 23:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.rename_table('tags', 'queues')
    op.alter_column('tasks', 'tag_key', new_column_name='queue_key')
    op.execute('ALTER TABLE tasks ADD COLUMN number INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE')
    op.drop_column('tasks', 'due')


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('tasks', sa.Column('due', sa.Text(), nullable=True))
    op.drop_column('tasks', 'number')
    op.alter_column('tasks', 'queue_key', new_column_name='tag_key')
    op.rename_table('queues', 'tags')
